path exclusion in no longer os-dependent
econchick/interrogate pull request #56
Opened 2020-10-05 19:28 UTC by oriash93

# Hey, I just made a Pull Request!

## Description
Excluding path is no longer os-dependent, by using `os.path.normpath`.

## Motivation and Context
Fixes #51 

## Have you tested this? If so, how?
I ran `interrogate` with these changes over relevant cases and it works for me.
No additional unit tests required.

## Checklist for PR author(s)

- [X] Changes are covered by unit tests (no major decrease in code coverage %).
- [X] All tests pass.
- [X] Docstring coverage is **100%** via `tox -e docs` or `interrogate -c pyproject.toml` (I mean, we _should_ set a good example :smile:).
- [X] Updates to documentation:
    - [X] Document any relevant additions/changes in `README.rst`.
    - [X] Manually update **both** the `README.rst` _and_ `docs/index.rst` for any new/changed CLI flags.
    - [X] Any changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).  Find the appropriate next version in the project's [``__init__.py``](https://github.com/econchick/interrogate/blob/master/src/interrogate/__init__.py) file.

2020-10-06 12:26 UTC, s-weigand commented
Someone didn't [install the `pre-commit` hook](https://github.com/econchick/interrogate/blob/master/CONTRIBUTING.md) 😉

2020-10-06 21:39 UTC, econchick requested changes

2020-10-06 21:39 UTC, econchick commented on src/interrogate/coverage.py
> +            if any([f.startswith(os.path.normpath(exc)) for exc in self.excluded]):
hey @oriash93 - thanks for the PR! Glad it was just a small change :) It looks like formatting is failing the build. Can you run `tox -e lint` locally to take care of that, then push your changes up?

2020-10-11 16:52 UTC, s-weigand commented
@oriash93 if @econchick is fine with the proposed feature in #59 , could you change
```python
if any(
                [f.startswith(os.path.normpath(exc)) for exc in self.excluded]
            ):
```
to

```python
if any( fnmatch(f, exc) for exc in self.excluded ):
```

That way this PR could kill two birds with one stone.

2020-10-11 19:16 UTC, oriash93 commented
Whatever @econchick decides.

Also, on a different note - do you mind marking this PR or repo as eligible for hacktoberfest?

2020-10-11 20:03 UTC, s-weigand commented
Thinking about it, the replacement should be
```python
if any( fnmatch(f, exc + "*") for exc in self.excluded ):
```
or if the python 3.5 support was droped before
```python
if any( fnmatch(f, f"{exc}*") for exc in self.excluded ):
```

That way it won't break configs that work with the current `startswith` implementation.

```python
In [1]: fnmatch(r"project\tests\test_file.py", "project/tests")
Out[1]: False

In [2]: fnmatch(r"project\tests\test_file.py", "project/tests*")
Out[2]: True

In [3]: fnmatch(r"project\tests\test_file.py", "project/tests**")
Out[3]: True

In [4]: fnmatch(r"project\tests\test_file.py", "project/tests***")
Out[4]: True

In [5]: fnmatch(r"project\tests\test_file.py", "project/tests****")
Out[5]: True
```

2020-10-11 21:16 UTC, econchick commented
Thanks @oriash93 @s-weigand (btw I labeled the repo w/ `hacktoberfest` - will that be enough?)

I'm cool with `fnmatch` if it makes #59 easier, although I'm not sure it does. I guess it depends on what's wanted: if we want to support _regexes_, then `fnmatch` may not be the best way since it [does not support `re` regex](https://docs.python.org/3/library/fnmatch.html). If #59 just wants to support unix-style wildcards, then it should be enough. That said, I'm not that familiar with `fnmatch` myself, so I could be wrong :)

2020-10-11 22:32 UTC, s-weigand commented
`fnmatch` uses unix-style glob patterns, which I guess most people are more familiar with than RegEx.
At least I hear all the time "I'm scared of RegEx" or "I never understood RegEx" 😋 
Also `fnmatch` is the way other tools like `flake8` handle their file matching.

In #59 I was just asking for a less explicit/ more general way to exclude files, so glob patterns are totaly awesome for me. 😄

2020-10-22 06:15 UTC, oriash93 commented
pinging @econchick

2020-11-03 21:42 UTC, econchick commented
Thanks so much! Sorry for the delay - I was on vacation for the past week and a half 😄

2020-11-03 21:42 UTC, merged

2020-11-03 22:14 UTC, econchick commented
FYI this has been released (finally) in [1.3.2](https://pypi.org/project/interrogate/1.3.2/) 🎉  - thanks again for you're help @oriash93 & @s-weigand 🥇